// Mode 4 — Jigsaw: a zoomable map of LA.
// You assemble a map from loose pieces, then tap a piece to ZOOM into it and
// assemble the next level down — regions → groups of neighborhoods → individual
// neighborhoods. Every level is capped at a handful of pieces; a piece's shape
// is the union of its children, so zooming always reveals the same shape broken
// into smaller parts. A "go up" control zooms back out.
//
// The tree, shapes, and sibling adjacency are generated by build-puzzle-shapes.
import { geoMercator } from 'd3-geo';
import { el, clear, shuffle } from '../ui/dom.js';
import { modeScreen } from '../ui/chrome.js';
import hierarchy from '../data/hierarchy.json';
import shapes from '../data/puzzle-shapes.json';
import adjacency from '../data/puzzle-adjacency.json';
import { store } from '../store.js';

const SVG_NS = 'http://www.w3.org/2000/svg';
const VB = 1000; // square user-space viewBox
const SNAP = 135; // connection radius in user units (~48px on a phone)

const NODES = hierarchy.nodes;
const ROOT = hierarchy.root;

// Debug toggle (persists across levels): skip the explode intro and drop straight
// into the assembled map, so you can test zooming in and out quickly.
let skipExplode = false;
const childrenOf = (id) => NODES[id].children || [];
const hasChildren = (id) => childrenOf(id).length > 0;
const isAdjacent = (a, b) => adjacency[a]?.includes(b) ?? false;

// Project a node's children into board coords. Each child's path is drawn at its
// TRUE position, so two pieces are correctly placed when their translates match.
function project(nodeId) {
  const kids = childrenOf(nodeId);
  const fc = {
    type: 'FeatureCollection',
    features: kids.map((id) => ({ type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [shapes[id]] } })),
  };
  const fit = kids.some((id) => hasChildren(id)) ? 460 : 600; // group pieces are bigger
  const m = (VB - fit) / 2;
  const proj = geoMercator().fitExtent([[m, m], [VB - m, VB - m]], fc);
  return kids.map((id) => {
    const ring = shapes[id].map((c) => proj(c));
    const xs = ring.map((p) => p[0]);
    const ys = ring.map((p) => p[1]);
    const minX = Math.min(...xs);
    const minY = Math.min(...ys);
    return {
      id,
      label: NODES[id].label,
      zoomable: hasChildren(id),
      d: 'M' + ring.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join('L') + 'Z',
      cx: ring.reduce((s, p) => s + p[0], 0) / ring.length,
      cy: ring.reduce((s, p) => s + p[1], 0) / ring.length,
      minX,
      minY,
      w: Math.max(...xs) - minX,
      h: Math.max(...ys) - minY,
    };
  });
}

export function mountJigsaw(app, { back }) {
  runNode(app, { back }, ROOT, {});
}

// Render one node's puzzle. `assembled:true` skips the explode intro and shows
// the map already solved (used when zooming back out to a parent).
function runNode(app, { back }, nodeId, { assembled = false }) {
  const node = NODES[nodeId];
  const pieces = project(nodeId);
  const goUp = () => (node.parent ? runNode(app, { back }, node.parent, { assembled: true }) : back());

  const svg = document.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('viewBox', `0 0 ${VB} ${VB}`);
  svg.setAttribute('class', 'jig');
  const pieceLayer = document.createElementNS(SVG_NS, 'g');
  svg.append(pieceLayer);

  const order = [];
  const counter = el('span', { class: 'jig-count' });
  let solved = false;
  let ready = false;
  let zoomMode = false;
  let drag = null;

  const apply = (rec) => rec.g.setAttribute('transform', `translate(${rec.tx.toFixed(1)} ${rec.ty.toFixed(1)})`);
  const lockedList = () => order.filter((r) => r.locked);

  function refreshCounter() {
    const remaining = order.filter((r) => !r.locked).length;
    counter.textContent = remaining === 0 ? 'Done!' : `${remaining} to place`;
    if (remaining === 0 && !solved) {
      solved = true;
      enterSolved(true);
    }
  }

  function enterSolved(withToast) {
    banner.classList.add('done');
    counter.textContent = 'Done!';
    if (order.some((r) => r.p.zoomable)) {
      zoomMode = true;
      order.forEach((r) => r.p.zoomable && r.g.classList.add('zoomable'));
      hint.textContent = '👆 Tap a piece to zoom in';
    } else {
      hint.textContent = 'Solved!';
    }
    if (withToast) showToast(`${node.label} solved!`);
  }

  function wouldConnect(rec) {
    const locked = lockedList();
    if (locked.length) {
      const o = locked[0];
      const positioned = Math.hypot(rec.tx - o.tx, rec.ty - o.ty) < SNAP;
      if (positioned && locked.some((l) => isAdjacent(rec.p.id, l.p.id))) return { tx: o.tx, ty: o.ty };
      return null;
    }
    for (const q of order) {
      if (q === rec || q.locked) continue;
      if (Math.hypot(rec.tx - q.tx, rec.ty - q.ty) < SNAP && isAdjacent(rec.p.id, q.p.id)) {
        return { tx: q.tx, ty: q.ty, seed: q };
      }
    }
    return null;
  }

  function place(rec, res) {
    rec.tx = res.tx;
    rec.ty = res.ty;
    rec.locked = true;
    rec.g.classList.add('placed');
    rec.g.classList.remove('jig-near');
    apply(rec);
    if (res.seed) {
      res.seed.locked = true;
      res.seed.g.classList.add('placed');
    }
    store.markSeen(rec.p.id);
    refreshCounter();
  }

  function snapAll() {
    order.forEach((rec) => {
      rec.tx = 0;
      rec.ty = 0;
      rec.locked = true;
      rec.g.classList.remove('jig-near', 'exploding', 'dragging');
      rec.g.classList.add('placed');
      apply(rec);
    });
  }

  function autosolve() {
    if (!ready || solved) return;
    snapAll();
    refreshCounter();
  }

  // Snap to solved immediately, regardless of the explode intro (for the "skip"
  // toggle so it works even mid-intro).
  function forceSolve() {
    if (solved) return;
    snapAll();
    ready = true;
    solved = true;
    enterSolved(false);
  }

  // Camera-zoom into a child piece, then open its puzzle.
  function zoomInto(rec) {
    if (!rec.p.zoomable) return;
    zoomMode = false;
    order.forEach((r) => {
      if (r === rec) return;
      r.g.style.transition = 'opacity 0.4s ease';
      r.g.style.opacity = '0';
    });
    const pad = 26;
    const target = [rec.p.minX - pad, rec.p.minY - pad, rec.p.w + 2 * pad, rec.p.h + 2 * pad];
    const start = [0, 0, VB, VB];
    const t0 = performance.now();
    const dur = 600;
    const ease = (t) => 1 - Math.pow(1 - t, 3);
    function frame(now) {
      const k = Math.min(1, (now - t0) / dur);
      const e = ease(k);
      svg.setAttribute('viewBox', start.map((s, i) => (s + (target[i] - s) * e).toFixed(1)).join(' '));
      if (k < 1) requestAnimationFrame(frame);
      else runNode(app, { back }, rec.p.id, {});
    }
    requestAnimationFrame(frame);
  }

  function toUser(evt) {
    const pt = svg.createSVGPoint();
    pt.x = evt.clientX;
    pt.y = evt.clientY;
    const u = pt.matrixTransform(svg.getScreenCTM().inverse());
    return [u.x, u.y];
  }

  function startDrag(rec, e) {
    if (!ready) return;
    if (zoomMode) {
      e.preventDefault();
      zoomInto(rec);
      return;
    }
    e.preventDefault();
    const [ux, uy] = toUser(e);
    if (rec.locked) {
      const locks = lockedList();
      locks.forEach((r) => r.g.classList.add('dragging'));
      drag = { mode: 'group', ux, uy, starts: locks.map((r) => ({ r, tx: r.tx, ty: r.ty })) };
    } else {
      pieceLayer.append(rec.g);
      rec.g.classList.add('dragging');
      drag = { mode: 'free', rec, ux, uy, tx: rec.tx, ty: rec.ty };
    }
    svg.setPointerCapture(e.pointerId);
  }
  svg.addEventListener('pointermove', (e) => {
    if (!drag) return;
    const [ux, uy] = toUser(e);
    const dx = ux - drag.ux;
    const dy = uy - drag.uy;
    if (drag.mode === 'free') {
      drag.rec.tx = drag.tx + dx;
      drag.rec.ty = drag.ty + dy;
      apply(drag.rec);
      drag.rec.g.classList.toggle('jig-near', !!wouldConnect(drag.rec));
    } else {
      for (const s of drag.starts) {
        s.r.tx = s.tx + dx;
        s.r.ty = s.ty + dy;
        apply(s.r);
      }
    }
  });
  const endDrag = () => {
    if (!drag) return;
    if (drag.mode === 'free') {
      drag.rec.g.classList.remove('dragging', 'jig-near');
      const res = wouldConnect(drag.rec);
      if (res) place(drag.rec, res);
    } else {
      drag.starts.forEach((s) => s.r.g.classList.remove('dragging'));
    }
    drag = null;
  };
  svg.addEventListener('pointerup', endDrag);
  svg.addEventListener('pointercancel', endDrag);

  // --- piece creation + scatter ---
  const MARGIN = 215;
  const CENTER = VB / 2;
  const clamp = (v) => Math.max(MARGIN, Math.min(VB - MARGIN, v));
  function scatterTranslate(p, k, count) {
    const angle = ((k + 0.5) / count) * Math.PI * 2 + (Math.random() - 0.5) * 0.3;
    const r = 300;
    return [clamp(CENTER + Math.cos(angle) * r) - p.cx, clamp(CENTER + Math.sin(angle) * r) - p.cy];
  }

  function makePiece(p) {
    const g = document.createElementNS(SVG_NS, 'g');
    g.setAttribute('class', 'jig-piece');
    const path = document.createElementNS(SVG_NS, 'path');
    path.setAttribute('d', p.d);
    path.setAttribute('class', 'jig-shape');
    const label = document.createElementNS(SVG_NS, 'text');
    label.setAttribute('x', p.cx);
    label.setAttribute('y', p.cy);
    label.setAttribute('class', 'jig-label');
    label.setAttribute('text-anchor', 'middle');
    label.setAttribute('dominant-baseline', 'central');
    label.textContent = p.label;
    g.append(path, label);
    const rec = { p, g, tx: 0, ty: 0, locked: false };
    g.addEventListener('pointerdown', (e) => startDrag(rec, e));
    pieceLayer.append(g);
    return rec;
  }

  const scattered = shuffle(pieces);
  scattered.forEach((p, k) => {
    const rec = makePiece(p);
    const [tx, ty] = scatterTranslate(p, k, scattered.length);
    rec.tx = tx;
    rec.ty = ty;
    order.push(rec);
  });

  const hint = el('span', { class: 'jig-hint' }, '');
  counter.textContent = `${order.length} to place`;

  const skipBox = el('input', {
    type: 'checkbox',
    onChange: (e) => {
      skipExplode = e.currentTarget.checked;
      if (skipExplode) forceSolve();
    },
  });
  skipBox.checked = skipExplode;
  const banner = el('div', { class: 'jig-banner' }, [
    hint,
    el('div', { class: 'jig-banner-right' }, [
      el('label', { class: 'jig-skip', title: 'Debug: skip the explode intro' }, [skipBox, 'skip']),
      el('button', { class: 'jig-up', onClick: goUp, title: 'Zoom out' }, '↑ up'),
      el('button', { class: 'jig-debug', onClick: autosolve, title: 'Debug: auto-solve' }, 'Solve'),
      counter,
    ]),
  ]);

  const boardWrap = el('div', { class: 'jig-board' }, [svg]);
  function showToast(msg) {
    const t = el('div', { class: 'jig-toast' }, msg);
    boardWrap.append(t);
    requestAnimationFrame(() => t.classList.add('show'));
    setTimeout(() => {
      t.classList.remove('show');
      setTimeout(() => t.remove(), 300);
    }, 2600);
  }

  if (assembled || skipExplode) {
    // Show the map already solved — zoomed back out to a parent, or the "skip
    // explode" debug toggle is on.
    snapAll();
    ready = true;
    solved = true;
    enterSolved(false);
  } else {
    // Explode intro: show assembled for a beat, then fly pieces out to scatter.
    hint.textContent = 'Putting the map together…';
    order.forEach((rec) => {
      rec.g.classList.add('exploding');
      rec.g.setAttribute('transform', 'translate(0 0)');
    });
    requestAnimationFrame(() => {
      setTimeout(() => {
        order.forEach((rec) => apply(rec));
        hint.textContent = 'Fit the pieces back together.';
        setTimeout(() => {
          order.forEach((rec) => rec.g.classList.remove('exploding'));
          ready = true;
        }, 650);
      }, 850);
    });
  }

  clear(app);
  app.append(
    modeScreen(node.label, goUp, [banner, boardWrap], {
      note: node.parent ? NODES[node.parent].label : '',
      bodyClass: 'jig-body',
    }),
  );
}
