// Mode 4 — Jigsaw: a zoomable map of LA.
// Assemble a map from loose pieces, then tap a piece to ZOOM into it and assemble
// the next level down — regions → groups of neighborhoods → individual hoods.
// Every level is capped (CAP=6 pieces); a piece's shape is the union of its
// children, so zooming reveals the same shape split into parts. A breadcrumb
// shows how deep you are; "↑ up" (and the breadcrumb) zoom back out.
//
// The tree, shapes, and sibling adjacency are generated by build-puzzle-shapes.
import { geoMercator } from 'd3-geo';
import { el, clear, shuffle } from '../ui/dom.js';
import { modeScreen } from '../ui/chrome.js';
import hierarchy from '../data/hierarchy.json';
import shapes from '../data/puzzle-shapes.json';
import adjacency from '../data/puzzle-adjacency.json';
import { store } from '../store.js';

const SVG_NS = 'http://www.w3.org/2000/svg';
const VB_W = 1000; // user-space width; height is derived from the board's aspect
const SNAP = 150; // connection radius in user units
const FILL = 0.84; // fraction of the board width the assembled map fills

// Distinct pastel fills so joined-up pieces are easy to tell apart (assigned by
// sibling index; ≤ CAP pieces per level so each gets its own).
const PALETTE = ['#8ecaa3', '#f2c673', '#9bb8ec', '#ec9f9b', '#bda9e0', '#7ecabf', '#d9b483'];

const NODES = hierarchy.nodes;
const ROOT = hierarchy.root;
const childrenOf = (id) => NODES[id].children || [];
const hasChildren = (id) => childrenOf(id).length > 0;
const isAdjacent = (a, b) => adjacency[a]?.includes(b) ?? false;
const pathIds = (id) => {
  const out = [];
  for (let cur = id; cur; cur = NODES[cur].parent) out.unshift(cur);
  return out;
};

// Debug toggle (persists across levels): skip the explode intro.
let skipExplode = false;

// Project a node's children into a vbW×vbH board. Each child's path is at its
// TRUE position, so pieces are placed correctly when their translates match.
function project(nodeId, vbW, vbH) {
  const kids = childrenOf(nodeId);
  const fc = {
    type: 'FeatureCollection',
    features: kids.map((id) => ({ type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [shapes[id]] } })),
  };
  const bw = vbW * FILL;
  const bh = vbH * FILL;
  const proj = geoMercator().fitExtent([[(vbW - bw) / 2, (vbH - bh) / 2], [(vbW + bw) / 2, (vbH + bh) / 2]], fc);
  const toPath = (lnglat) => 'M' + lnglat.map((c) => proj(c)).map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join('L') + 'Z';
  return kids.map((id, i) => {
    const ring = shapes[id].map((c) => proj(c));
    const xs = ring.map((p) => p[0]);
    const ys = ring.map((p) => p[1]);
    const minX = Math.min(...xs);
    const minY = Math.min(...ys);
    // Zoomable pieces carry faint outlines of their own children, so you can
    // SEE that they break down (and tapping will reveal those sections).
    const inner = hasChildren(id) ? childrenOf(id).map((gid) => toPath(shapes[gid])) : null;
    return {
      id,
      label: NODES[id].label,
      zoomable: hasChildren(id),
      color: PALETTE[i % PALETTE.length],
      inner,
      d: 'M' + ring.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join('L') + 'Z',
      cx: ring.reduce((s, p) => s + p[0], 0) / ring.length,
      cy: ring.reduce((s, p) => s + p[1], 0) / ring.length,
      minX,
      minY,
      w: Math.max(...xs) - minX,
      h: Math.max(...ys) - minY,
    };
  });
}

// Lay a label out as up to two balanced lines (long region/area names overflow
// a single line and read poorly). Returns the lines.
function wrapLabel(str) {
  const words = str.split(' ');
  if (words.length <= 1) return [str];
  let best = 1;
  let bestDiff = Infinity;
  for (let i = 1; i < words.length; i++) {
    const a = words.slice(0, i).join(' ').length;
    const b = words.slice(i).join(' ').length;
    if (Math.abs(a - b) < bestDiff) {
      bestDiff = Math.abs(a - b);
      best = i;
    }
  }
  return [words.slice(0, best).join(' '), words.slice(best).join(' ')];
}

export function mountJigsaw(app, { back }) {
  runNode(app, { back }, ROOT, {});
}

// Render one node's puzzle. `assembled` skips the explode intro (shows it solved);
// `zoomOutFrom` is the child we came from when going up — used to animate a
// reverse zoom from that child's spot out to the full parent.
function runNode(app, { back }, nodeId, { assembled = false, zoomOutFrom = null }) {
  const node = NODES[nodeId];
  const goUp = () => (node.parent ? runNode(app, { back }, node.parent, { assembled: true, zoomOutFrom: nodeId }) : back());
  const goTo = (id) => (id === nodeId ? null : runNode(app, { back }, id, { assembled: true, zoomOutFrom: pathIds(nodeId)[pathIds(id).length] }));

  const svg = document.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('class', 'jig');
  svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');
  const pieceLayer = document.createElementNS(SVG_NS, 'g');
  svg.append(pieceLayer);

  const order = [];
  const counter = el('span', { class: 'jig-count' });
  let solved = false;
  let ready = false;
  let zoomMode = false;
  let drag = null;
  let vbH = VB_W; // updated once the board is measured

  const fullVB = () => [0, 0, VB_W, vbH];
  const apply = (rec) => rec.g.setAttribute('transform', `translate(${rec.tx.toFixed(1)} ${rec.ty.toFixed(1)})`);
  const lockedList = () => order.filter((r) => r.locked);

  function refreshCounter() {
    const remaining = order.filter((r) => !r.locked).length;
    counter.textContent = remaining === 0 ? 'Done!' : `${remaining} left`;
    if (remaining === 0 && !solved) {
      solved = true;
      enterSolved(true);
    }
  }

  function enterSolved(withToast) {
    banner.classList.add('done');
    counter.textContent = 'Done!';
    if (order.some((r) => r.p.zoomable)) {
      zoomMode = true;
      order.forEach((r) => r.p.zoomable && r.g.classList.add('zoomable'));
      hint.textContent = '👆 Tap a piece to zoom in';
    } else {
      hint.textContent = 'Solved!';
    }
    if (withToast) showToast(`${node.label} solved!`);
  }

  function wouldConnect(rec) {
    const locked = lockedList();
    if (locked.length) {
      const o = locked[0];
      const positioned = Math.hypot(rec.tx - o.tx, rec.ty - o.ty) < SNAP;
      if (positioned && locked.some((l) => isAdjacent(rec.p.id, l.p.id))) return { tx: o.tx, ty: o.ty };
      return null;
    }
    for (const q of order) {
      if (q === rec || q.locked) continue;
      if (Math.hypot(rec.tx - q.tx, rec.ty - q.ty) < SNAP && isAdjacent(rec.p.id, q.p.id)) {
        return { tx: q.tx, ty: q.ty, seed: q };
      }
    }
    return null;
  }

  function place(rec, res) {
    rec.tx = res.tx;
    rec.ty = res.ty;
    rec.locked = true;
    rec.g.classList.add('placed');
    rec.g.classList.remove('jig-near');
    apply(rec);
    if (res.seed) {
      res.seed.locked = true;
      res.seed.g.classList.add('placed');
    }
    store.markSeen(rec.p.id);
    refreshCounter();
  }

  function snapAll() {
    order.forEach((rec) => {
      rec.tx = 0;
      rec.ty = 0;
      rec.locked = true;
      rec.g.classList.remove('jig-near', 'exploding', 'dragging');
      rec.g.classList.add('placed');
      apply(rec);
    });
  }
  function autosolve() {
    if (!ready || solved) return;
    snapAll();
    refreshCounter();
  }
  function forceSolve() {
    if (solved) return;
    snapAll();
    ready = true;
    solved = true;
    enterSolved(false);
  }

  function animateZoom(from, to, onDone) {
    const t0 = performance.now();
    const dur = 580;
    const ease = (t) => 1 - Math.pow(1 - t, 3);
    function frame(now) {
      const k = Math.min(1, (now - t0) / dur);
      const e = ease(k);
      svg.setAttribute('viewBox', from.map((s, i) => (s + (to[i] - s) * e).toFixed(1)).join(' '));
      if (k < 1) requestAnimationFrame(frame);
      else if (onDone) onDone();
    }
    requestAnimationFrame(frame);
  }
  const pieceBox = (p) => {
    const pad = Math.max(p.w, p.h) * 0.12 + 20;
    return [p.minX - pad, p.minY - pad, p.w + 2 * pad, p.h + 2 * pad];
  };

  function zoomInto(rec) {
    if (!rec.p.zoomable) return;
    zoomMode = false;
    order.forEach((r) => {
      if (r === rec) return;
      r.g.style.transition = 'opacity 0.4s ease';
      r.g.style.opacity = '0';
    });
    animateZoom(fullVB(), pieceBox(rec.p), () => runNode(app, { back }, rec.p.id, {}));
  }

  function toUser(evt) {
    const pt = svg.createSVGPoint();
    pt.x = evt.clientX;
    pt.y = evt.clientY;
    const u = pt.matrixTransform(svg.getScreenCTM().inverse());
    return [u.x, u.y];
  }

  function startDrag(rec, e) {
    if (!ready) return;
    if (zoomMode) {
      e.preventDefault();
      zoomInto(rec);
      return;
    }
    e.preventDefault();
    const [ux, uy] = toUser(e);
    if (rec.locked) {
      const locks = lockedList();
      locks.forEach((r) => r.g.classList.add('dragging'));
      drag = { mode: 'group', ux, uy, starts: locks.map((r) => ({ r, tx: r.tx, ty: r.ty })) };
    } else {
      pieceLayer.append(rec.g);
      rec.g.classList.add('dragging');
      drag = { mode: 'free', rec, ux, uy, tx: rec.tx, ty: rec.ty };
    }
    svg.setPointerCapture(e.pointerId);
  }
  svg.addEventListener('pointermove', (e) => {
    if (!drag) return;
    const [ux, uy] = toUser(e);
    const dx = ux - drag.ux;
    const dy = uy - drag.uy;
    if (drag.mode === 'free') {
      drag.rec.tx = drag.tx + dx;
      drag.rec.ty = drag.ty + dy;
      apply(drag.rec);
      drag.rec.g.classList.toggle('jig-near', !!wouldConnect(drag.rec));
    } else {
      for (const s of drag.starts) {
        s.r.tx = s.tx + dx;
        s.r.ty = s.ty + dy;
        apply(s.r);
      }
    }
  });
  const endDrag = () => {
    if (!drag) return;
    if (drag.mode === 'free') {
      drag.rec.g.classList.remove('dragging', 'jig-near');
      const res = wouldConnect(drag.rec);
      if (res) place(drag.rec, res);
    } else {
      drag.starts.forEach((s) => s.r.g.classList.remove('dragging'));
    }
    drag = null;
  };
  svg.addEventListener('pointerup', endDrag);
  svg.addEventListener('pointercancel', endDrag);

  function scatterTranslate(p, k, count) {
    const angle = ((k + 0.5) / count) * Math.PI * 2 + (Math.random() - 0.5) * 0.25;
    const X = VB_W / 2 + Math.cos(angle) * VB_W * 0.31;
    const Y = vbH / 2 + Math.sin(angle) * vbH * 0.33;
    const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
    return [clamp(X, VB_W * 0.16, VB_W * 0.84) - p.cx, clamp(Y, vbH * 0.13, vbH * 0.87) - p.cy];
  }

  function makePiece(p) {
    const g = document.createElementNS(SVG_NS, 'g');
    g.setAttribute('class', `jig-piece${p.zoomable ? ' zoomy' : ' leaf'}`);
    g.dataset.cx = p.cx.toFixed(1);
    g.dataset.cy = p.cy.toFixed(1);
    g.style.setProperty('--fill', p.color);
    const path = document.createElementNS(SVG_NS, 'path');
    path.setAttribute('d', p.d);
    path.setAttribute('class', 'jig-shape');
    g.append(path);
    // Faint inner subdivisions for zoomable pieces.
    if (p.inner) {
      for (const d of p.inner) {
        const ip = document.createElementNS(SVG_NS, 'path');
        ip.setAttribute('d', d);
        ip.setAttribute('class', 'jig-inner');
        g.append(ip);
      }
    }
    // Auto-size the label to the piece so it actually fits and stays readable.
    const lines = wrapLabel(p.label);
    const maxChars = Math.max(...lines.map((l) => l.length));
    const byWidth = (p.w * 0.94) / (maxChars * 0.56);
    const byHeight = (p.h * 0.6) / lines.length;
    const fs = Math.max(20, Math.min(54, byWidth, byHeight));
    const LH = fs * 1.02;
    const label = document.createElementNS(SVG_NS, 'text');
    label.setAttribute('class', 'jig-label');
    label.setAttribute('text-anchor', 'middle');
    label.style.fontSize = `${fs.toFixed(1)}px`;
    label.style.strokeWidth = `${(fs * 0.2).toFixed(1)}px`;
    lines.forEach((ln, i) => {
      const ts = document.createElementNS(SVG_NS, 'tspan');
      ts.setAttribute('x', p.cx);
      ts.setAttribute('y', (p.cy + (i - (lines.length - 1) / 2) * LH).toFixed(1));
      ts.setAttribute('dominant-baseline', 'central');
      ts.textContent = ln;
      label.append(ts);
    });
    g.append(label);
    const rec = { p, g, tx: 0, ty: 0, locked: false };
    g.addEventListener('pointerdown', (e) => startDrag(rec, e));
    pieceLayer.append(g);
    return rec;
  }

  // Build pieces + run the intro/zoom. Called once the board has been measured.
  function setup() {
    const pieces = project(nodeId, VB_W, vbH);
    const scattered = shuffle(pieces);
    scattered.forEach((p, k) => {
      const rec = makePiece(p);
      const [tx, ty] = scatterTranslate(p, k, scattered.length);
      rec.tx = tx;
      rec.ty = ty;
      order.push(rec);
    });
    counter.textContent = `${order.length} left`;

    if (assembled || skipExplode) {
      snapAll();
      ready = true;
      solved = true;
      enterSolved(false);
      if (zoomOutFrom) {
        const from = pieces.find((p) => p.id === zoomOutFrom);
        if (from) animateZoom(pieceBox(from), fullVB());
      }
    } else {
      hint.textContent = 'Putting the map together…';
      order.forEach((rec) => {
        rec.g.classList.add('exploding');
        rec.g.setAttribute('transform', 'translate(0 0)');
      });
      requestAnimationFrame(() => {
        setTimeout(() => {
          order.forEach((rec) => apply(rec));
          hint.textContent = 'Fit the pieces back together.';
          setTimeout(() => {
            order.forEach((rec) => rec.g.classList.remove('exploding'));
            ready = true;
          }, 650);
        }, 850);
      });
    }
  }

  // --- chrome ---
  const hint = el('span', { class: 'jig-hint' }, '');
  const skipBox = el('input', {
    type: 'checkbox',
    onChange: (e) => {
      skipExplode = e.currentTarget.checked;
      if (skipExplode) forceSolve();
    },
  });
  skipBox.checked = skipExplode;
  const banner = el('div', { class: 'jig-banner' }, [
    hint,
    el('div', { class: 'jig-banner-right' }, [
      el('label', { class: 'jig-skip', title: 'Debug: skip the explode intro' }, [skipBox, 'skip']),
      el('button', { class: 'jig-up', onClick: goUp, title: 'Zoom out' }, '↑ up'),
      el('button', { class: 'jig-debug', onClick: autosolve, title: 'Debug: auto-solve' }, 'Solve'),
      counter,
    ]),
  ]);

  const crumbs = pathIds(nodeId);
  const breadcrumb = el(
    'div',
    { class: 'jig-crumbs' },
    crumbs.flatMap((id, i) => {
      const last = i === crumbs.length - 1;
      const seg = el('button', { class: `jig-crumb${last ? ' current' : ''}`, onClick: last ? null : () => goTo(id) }, NODES[id].label);
      return last ? [seg] : [seg, el('span', { class: 'jig-crumb-sep' }, '›')];
    }),
  );

  const boardWrap = el('div', { class: 'jig-board' }, [svg]);
  function showToast(msg) {
    const t = el('div', { class: 'jig-toast' }, msg);
    boardWrap.append(t);
    requestAnimationFrame(() => t.classList.add('show'));
    setTimeout(() => {
      t.classList.remove('show');
      setTimeout(() => t.remove(), 300);
    }, 2600);
  }

  clear(app);
  app.append(modeScreen('Jigsaw', goUp, [breadcrumb, banner, boardWrap], { bodyClass: 'jig-body' }));

  // Measure the board, set a matching viewBox (so the map fills it with no
  // letterboxing), then build the pieces.
  requestAnimationFrame(() => {
    const w = boardWrap.clientWidth || 360;
    const h = boardWrap.clientHeight || 360;
    vbH = Math.round((VB_W * h) / w);
    svg.setAttribute('viewBox', `0 0 ${VB_W} ${vbH}`);
    setup();
  });
}
