// Freeways (prototype): the puzzle data and its small rules — no DOM.
// Each puzzle: drive from one place to another. The route is a few freeway
// "legs" in driving order (one per freeway: the 101, then the 405, then the
// 10), plus a decoy or two that aren't on it. Generated by
// scripts/build-freeways.mjs, easier (fewer legs) first.
import DATA from '../data/freeways.json';
import { decodeRing } from '../jigsaw/polyline.js';

export const REFS = DATA.refs; // '10' → { kind: 'I' | 'US' | 'CA', name }
export const PUZZLES = DATA.puzzles;
export const NETWORK = DATA.network; // [{ ref, line }] — every freeway, for the map
export const idOf = (p) => `${p.from}→${p.to}`;

const decoded = new Map();
export const lineOf = (block) => {
  if (!decoded.has(block.line)) decoded.set(block.line, decodeRing(block.line));
  return decoded.get(block.line);
};

// "the 10", "the 101" — how Angelenos say it.
export const say = (ref) => `the ${ref}`;

export * from './rules.js';
import { nextIndex as nextIn } from './rules.js';
// (Shadows the generic one from rules.js, bound to this data.)
export const nextIndex = (isSolved, from = -1) => nextIn(isSolved, from, PUZZLES.length, (i) => idOf(PUZZLES[i]));
