// Freeways (prototype): the puzzle data and its small rules — no DOM.
// Each puzzle: drive from one place to another; the route is a few freeway
// "blocks" (one per freeway along the way) plus a decoy or two that aren't on
// it. Generated by scripts/build-freeways.mjs, easier (fewer blocks) first.
import DATA from '../data/freeways.json';
import { decodeRing } from '../jigsaw/polyline.js';

export const REFS = DATA.refs; // '10' → { kind: 'I' | 'US' | 'CA', name }
export const PUZZLES = DATA.puzzles;
export const idOf = (p) => `${p.from}→${p.to}`;

const decoded = new Map();
export const lineOf = (block) => {
  if (!decoded.has(block.line)) decoded.set(block.line, decodeRing(block.line));
  return decoded.get(block.line);
};

// "the 10", "the 101" — how Angelenos say it.
export const say = (ref) => `the ${ref}`;

// Which puzzle to play next: the first unsolved one after `from` (wrapping),
// so play walks the easy → hard order and skipped ones come back around.
export function nextIndex(isSolved, from = -1) {
  const n = PUZZLES.length;
  for (let k = 1; k <= n; k++) {
    const i = (from + k + n) % n;
    if (!isSolved(idOf(PUZZLES[i]))) return i;
  }
  return (from + 1 + n) % n; // all solved: just keep going round
}

// Is a block dropped with offset (dx, dy) from its true spot close enough to
// click in? `radius` scales with the map, so it feels the same at any zoom.
export const snaps = (dx, dy, radius) => Math.hypot(dx, dy) <= radius;

// Misses on one block → how much help: 0 nothing, 1 a nudge, 2 its outline.
export const hintLevel = (misses) => (misses >= 3 ? 2 : misses >= 2 ? 1 : 0);
